image:
  repository: jaegertracing/all-in-one
  tag: 1.11.0
## Specify a imagePullPolicy
## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  query:
    type: NodePort
  agent:
    type: ClusterIP

config:
  # Custom ENV and CLI args passed to Jaeger
  env:
    SPAN_STORAGE_TYPE: memory
  args:
    - "--memory.max-traces=100000"

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 4Gi
    cpu: 0.5
  limits:
    memory: 5Gi
    cpu: 1
## Node labels and tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
nodeSelector: {}
tolerations: []
affinity: {}
