{{- if .Values.swarm.ingress.enabled -}}

{{- $root := . -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "swarm.fullname" $root }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{ toYaml .Values.swarm.ingress.annotations | indent 4 }}
{{- if and ($root.Values.swarm.ingress.tls.enabled) ($root.Values.swarm.ingress.tls.acmeEnabled) }}
    kubernetes.io/tls-acme: "true"
{{- end }}
spec:
{{- if $root.Values.swarm.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ template "swarm.fullname" $root }}-{{ $root.Release.Namespace }}.{{ $root.Values.swarm.ingress.domain }}
  {{- if $root.Values.swarm.ingress.tls.acmeEnabled }}
    secretName: {{ template "swarm.fullname" $root }}-ingress-tls
  {{- end }}
{{- end }}
  rules:
  - host: {{ template "swarm.fullname" $root }}-{{ $root.Release.Namespace }}.{{ $root.Values.swarm.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "swarm.fullname" $root }}-internal
          servicePort: 8500


{{- range $i, $e := until (int $root.Values.swarm.replicaCount) }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "swarm.fullname" $root }}-{{ $i }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{ toYaml $root.Values.swarm.ingress.annotations | indent 4 }}
{{- if and ($root.Values.swarm.ingress.tls.enabled) ($root.Values.swarm.ingress.tls.acmeEnabled) }}
    kubernetes.io/tls-acme: "true"
{{- end }}
spec:
{{- if $root.Values.swarm.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ template "swarm.fullname" $root }}-{{ $i }}-{{ $root.Release.Namespace }}.{{ $root.Values.swarm.ingress.domain }}
  {{- if $root.Values.swarm.ingress.tls.acmeEnabled }}
    secretName: {{ template "swarm.fullname" $root }}-ingress-tls-{{ $i }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ template "swarm.fullname" $root }}-{{ $i }}-{{ $root.Release.Namespace }}.{{ $root.Values.swarm.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "swarm.fullname" $root }}-internal-{{ $i }}
          servicePort: 8500
    {{- if $root.Values.swarm.ingress.exposeWebsocketRPC }}
      - path: /wsrpc
        backend:
          serviceName: {{ template "swarm.fullname" $root }}-internal-{{ $i }}
          servicePort: 8546
    {{- end }}
{{- end }}
{{- end }}
